name: Solar System

on:
    push:
        branches:
            - main
            - 'feature/*'

jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
            
          - name: Install Node
            uses: actions/setup-node@v4
            with:
                node_version: '16'
            
          - name: Install Dependencies
            run: npm install

          - name: Unit Testing
            run: npm test

          - name: Archieve Tests
            uses: actions/upload_artifact@v4
            with:
                name: Mocha-test-result
                path: test-results.xml
